"""Turn a studio agent-spec into the files that stand an agent up: a correct-by-
construction ``capabilities.env``, a non-secret ``agent.yaml``, a ``persona.yaml``,
and the secrets kept SEPARATE. This is the backend the setup wizard posts to, and the
mechanical enforcement of the env-flag rules (see nmem-migration-hive-handover.md §3):
a config written here cannot carry an inline comment, a bare non-boolean, an unmet
dependency, or a leaked key. Renderers are pure (return strings/dicts); ``write_agent``
is the thin side-effecting convenience.
"""
from __future__ import annotations

from nmem.agent_core.capabilities import CAPABILITIES, requires_closure

# Flags whose value is not a boolean toggle (they carry a value when enabled).
_VALUE_FLAGS = {"NMEM_SYM_DRIVES_OUTWARD_ACTIONS"}

# End-state cadence for the per-agent goal-lifecycle tick (agent_core._lifecycle_loop). Tunable;
# the lifecycle (impasse-tick / decompose / abandon-stale / reap) is not latency-sensitive.
_LIFECYCLE_TICK_SECONDS = 3600


def _flag_closure(enabled) -> set:
    """The dependency-complete flag set (every enabled flag's transitive ``requires`` pulled in)."""
    flags = set(enabled)
    for f in list(flags):
        flags |= requires_closure(f)
    return flags


def render_capabilities_env(enabled, *, agent_id: str = "", outward_actions: str = "explore") -> str:
    """Render ``capabilities.env`` from a set of enabled capability flags.

    GUARANTEES (the whole point): dependency-complete (every flag's `requires` are pulled
    in transitively), booleans only, comments only on their own line (never inline, which
    would crash env parsing), defaults omitted (only enabled flags written), grouped by
    capability area. Also auto-writes value-constraints the flags imply (e.g. RECALL_DRIVE
    needs RECALL_AGENT_ID = the agent's id)."""
    flags = _flag_closure(enabled)

    # group order = order the groups first appear in the capability map
    order: list[str] = []
    for c in CAPABILITIES.values():
        if c.group not in order:
            order.append(c.group)

    def value_for(f: str) -> str:
        return outward_actions if f == "NMEM_SYM_DRIVES_OUTWARD_ACTIONS" else "true"

    lines = [
        "# capabilities.env generated by nmem.agent_core.config_writer",
        "# dependency-complete; booleans only; no inline comments; defaults omitted",
        "",
    ]
    for g in order:
        gflags = sorted(f for f in flags if f in CAPABILITIES and CAPABILITIES[f].group == g)
        if not gflags:
            continue
        lines.append(f"# {g}")
        lines += [f"{f}={value_for(f)}" for f in gflags]
        lines.append("")

    # B-ii D2 (end-state): agent_core's _lifecycle_loop is the per-agent goal-lifecycle driver, so
    # the shared-graph dreamstate must NOT also run it (double-ticking the monotonic impasse counter).
    # Paired with agent.yaml goal_lifecycle.loop_enabled=true. Only meaningful when goals exist.
    if "NMEM_SYM_GOALS_ENABLED" in flags:
        lines.append("# goal-lifecycle (agent_core owns it — dreamstate skips it)")
        lines.append("NMEM_SYM_GOAL_LIFECYCLE_EXTERNAL=true")
        lines.append("")

    # value-constraints implied by enabled flags
    extras = []
    if "NMEM_SYM_RECALL_DRIVE_ENABLED" in flags and agent_id:
        extras.append(f"NMEM_SYM_RECALL_AGENT_ID={agent_id}")
    if extras:
        lines.append("# values")
        lines += extras
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def render_agent_yaml(
    *, agent_id: str, llm: dict, embedding: dict | None = None,
    symbol_graph: dict | None = None, pursuit: dict | None = None,
    db_env_key: str | None = None, db_url=None,
    belief: dict | None = None, policy: dict | None = None,
    actors: dict | None = None, autonomy: dict | None = None, hive: dict | None = None,
    goal_lifecycle: dict | None = None,
) -> str:
    """Render the NON-SECRET ``agent.yaml`` (structural config for agent_core.build_memory /
    build_symbol_graph / AgentRuntime). API keys are NOT written here — they are secrets
    (see ``split_secrets``). ``llm`` = {provider, base_url, model}; a key is stripped if present.
    ``actors`` = the declarative tool config (webhooks/openapi/mcp/a2a/plugins_dir) the actor seam
    reads; ``autonomy`` = {level, allow, deny} governing what the actor executor may run."""
    import yaml

    env_key = db_env_key or f"{agent_id.upper()}_DB_DSN_ASYNC"
    llm_clean = {k: v for k, v in (llm or {}).items() if k != "api_key" and v is not None}
    emb = dict(embedding or {"provider": "sentence-transformers",
                             "model": "all-MiniLM-L6-v2", "dimensions": 384})
    emb.pop("api_key", None)
    sg = dict(symbol_graph or {})
    sg.setdefault("enabled", True)
    sg.setdefault("domain", f"{agent_id}-cognition")

    # The agent's reasoning brain (what AgentRuntime.build_backend reads from backends.brain).
    # Note `url` not `base_url` — that's the key build_backend expects. The key is NEVER written:
    # api_key_env names the env var it is read from at boot (kept in secrets, not agent.yaml).
    brain = {"provider": llm_clean.get("provider", "openai"), "url": llm_clean.get("base_url"),
             "model": llm_clean.get("model"), "family": llm_clean.get("family", "generic")}
    if llm_clean.get("api_key_env"):
        brain["api_key_env"] = llm_clean["api_key_env"]
    brain = {k: v for k, v in brain.items() if v is not None}

    doc = {
        "db": {"env_key": env_key, "config_key": agent_id},
        "databases": {agent_id: {"url": db_url}},
        "backends": {"brain": brain},
        "nmem": {
            "embedding": emb,
            "llm": llm_clean,
            "belief": belief or {"default_trust": 0.5},
            "policy": policy or {"writers": ["system", agent_id], "max_chars_in_prompt": 4000},
        },
        "symbol_graph": sg,
    }
    if pursuit is not None:
        doc["pursuit"] = pursuit
    if actors:
        doc["actors"] = actors
    if autonomy:
        doc["autonomy"] = autonomy
    if hive:
        doc["hive"] = hive
    if goal_lifecycle:
        doc["goal_lifecycle"] = goal_lifecycle
    return yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)


def split_secrets(*, agent_id: str, llm_key: str = "", llm_key_env: str = "",
                  embed_key: str = "") -> dict:
    """The secrets to store OUT of agent.yaml (env-var -> value). The host writes these to
    its secret store; agent.yaml only references the env var. Empty values are dropped."""
    out = {}
    if llm_key:
        out[llm_key_env or f"{agent_id.upper()}_LLM_TOKEN"] = llm_key
    if embed_key:
        out[f"{agent_id.upper()}_EMBED_TOKEN"] = embed_key
    return out


def build_agent_files(spec: dict) -> dict:
    """One call from the wizard: a spec -> the files to write.

    spec keys: agent_id, enabled (flag set/list), persona (a Persona or dict), llm
    ({provider,base_url,model,api_key,api_key_env}), embedding, symbol_graph, pursuit,
    outward_actions, db_url. Returns {capabilities.env, agent.yaml, persona.yaml, secrets}.
    The three strings are written to the agent's config dir; `secrets` (env-var->value) goes
    to the secret store, never into a committed/shared file."""
    import yaml
    from nmem.agent_core.persona import Persona

    agent_id = spec["agent_id"]
    persona = spec.get("persona")
    if isinstance(persona, dict):
        persona = Persona.from_dict({**persona, "agent_id": persona.get("agent_id", agent_id)})
    llm = dict(spec.get("llm") or {})
    key = llm.pop("api_key", "")
    key_env = llm.get("api_key_env", "")   # a NAME, not a secret — stays in agent.yaml (backends.brain)
    if key and not key_env:                # a key with no env name → default one so it's resolvable
        key_env = f"{agent_id.upper()}_LLM_TOKEN"
        llm["api_key_env"] = key_env
    # embedding: strip the inline key, but leave an api_key_env so build_memory can resolve the
    # stored secret (split_secrets keeps it under <AGENT>_EMBED_TOKEN).
    emb = dict(spec.get("embedding") or {}) or None
    emb_key = emb.pop("api_key", "") if emb else ""
    if emb_key and emb is not None:
        emb["api_key_env"] = f"{agent_id.upper()}_EMBED_TOKEN"

    # B-ii D2 end-state: if this agent has goals, agent_core's _lifecycle_loop drives their lifecycle
    # (paired with NMEM_SYM_GOAL_LIFECYCLE_EXTERNAL=true in capabilities.env). Spec may override.
    goals_on = "NMEM_SYM_GOALS_ENABLED" in _flag_closure(spec.get("enabled") or set())
    goal_lifecycle = spec.get("goal_lifecycle")
    if goal_lifecycle is None and goals_on:
        goal_lifecycle = {"loop_enabled": True, "tick_seconds": _LIFECYCLE_TICK_SECONDS}

    # A shared_world hive member owns a distinct agent_id (agency is owner_agent-scoped to it). Stamp
    # it into the hive block so the generated config is self-contained (not reliant on a runtime default).
    hive = spec.get("hive")
    if isinstance(hive, dict) and str(hive.get("mode", "")).lower() == "shared_world":
        hive = {**hive, "agent_id": hive.get("agent_id") or agent_id}

    return {
        "capabilities.env": render_capabilities_env(
            spec.get("enabled") or set(), agent_id=agent_id,
            outward_actions=spec.get("outward_actions", "explore")),
        "agent.yaml": render_agent_yaml(
            agent_id=agent_id, llm=llm, embedding=emb,
            symbol_graph=spec.get("symbol_graph"), pursuit=spec.get("pursuit"),
            db_url=spec.get("db_url"), actors=spec.get("actors"), autonomy=spec.get("autonomy"),
            hive=hive, goal_lifecycle=goal_lifecycle),
        "persona.yaml": yaml.safe_dump(persona.to_dict(), sort_keys=False) if persona else "",
        "secrets": split_secrets(agent_id=agent_id, llm_key=key, llm_key_env=key_env,
                                 embed_key=emb_key),
    }


def write_agent(config_dir: str, spec: dict) -> dict:
    """Convenience: render + write agent.yaml / capabilities.env / persona.yaml into
    ``config_dir`` and RETURN the secrets dict (the caller stores those securely — they are
    never written here). Returns {"written": [...paths], "secrets": {...}}."""
    import os
    files = build_agent_files(spec)
    os.makedirs(config_dir, exist_ok=True)
    written = []
    for name in ("agent.yaml", "capabilities.env", "persona.yaml"):
        if files[name]:
            path = os.path.join(config_dir, name)
            with open(path, "w") as fh:
                fh.write(files[name])
            written.append(path)
    return {"written": written, "secrets": files["secrets"]}
