#!/usr/bin/env python3
"""Generate the configuration reference tables for docs/configuration.md.

nmem's config.py is the authoritative source: nested pydantic ``*Config(BaseModel)`` classes
whose fields carry attribute docstrings (``name: type = default`` followed by ``\"\"\"purpose\"\"\"``).
The top-level ``NmemConfig(BaseSettings)`` nests them under section names (``ltm: LTMConfig``),
loadable from TOML ``[ltm]`` keys or ``NMEM_LTM__FIELD`` env vars (prefix ``NMEM_``, nested
delimiter ``__``). This script extracts every field — TOML key, env var, type, default, and
purpose — grouped by section, so the doc can't drift from the code.

    python scripts/gen_config_reference.py src/nmem/config.py
"""
import re
import sys

CLASS = re.compile(r"^class (\w+)\((?:BaseModel|BaseSettings)\):")
FIELD = re.compile(r"^    ([a-z_]\w*)\s*:\s*(.+?)\s*=\s*(.+?)\s*$")
NESTED = re.compile(r"^(\w+Config)\(\)$")


def _short(s: str, n: int) -> str:
    s = " ".join(s.split())
    return s[: n - 1].rstrip() + "…" if len(s) > n else s


def parse_classes(lines):
    """{classname: [(field, type, default, purpose)]} + {classname: class-docstring}."""
    classes, docs = {}, {}
    i, n = 0, len(lines)
    cur = None
    while i < n:
        cm = CLASS.match(lines[i])
        if cm:
            cur = cm.group(1)
            classes[cur], docs[cur] = [], ""
            # class docstring on the next non-blank line
            k = i + 1
            while k < n and lines[k].strip() == "":
                k += 1
            if k < n and lines[k].strip().startswith('"""'):
                docs[cur] = lines[k].strip().strip('"').strip()
            i += 1
            continue
        if cur is not None:
            # dedent to module level (next class or top-level code) ends the class
            if lines[i] and not lines[i][0].isspace() and not lines[i].startswith("#"):
                cur = None
                continue
            fm = FIELD.match(lines[i])
            if fm:
                name, typ, default = fm.group(1), fm.group(2), fm.group(3)
                purpose, k = "", i + 1
                if k < n and lines[k].strip().startswith('"""'):
                    d = lines[k].strip()
                    if d.count('"""') >= 2 and len(d) > 5:          # single-line docstring
                        purpose = d.strip('"').strip()
                        k += 1
                    else:                                            # multi-line
                        buf, k = [d.replace('"""', "")], k + 1
                        while k < n and '"""' not in lines[k]:
                            buf.append(lines[k].strip())
                            k += 1
                        if k < n:
                            buf.append(lines[k].replace('"""', ""))
                        purpose = " ".join(x.strip() for x in buf if x.strip())
                        k += 1
                classes[cur].append((name, typ, default, purpose))
                i = k
                continue
        i += 1
    return classes, docs


def main() -> None:
    lines = open(sys.argv[1]).read().split("\n")
    classes, docs = parse_classes(lines)
    top = classes.get("NmemConfig", [])

    # section order + class→section map from NmemConfig; top-level scalars kept in order
    section_of, order, toplevel = {}, [], []
    for (name, typ, default, purpose) in top:
        nm = NESTED.match(default)
        if nm:
            section_of[nm.group(1)] = name
            order.append((name, nm.group(1)))
        else:
            toplevel.append((name, typ, default, purpose))

    total = len(toplevel) + sum(len(classes[c]) for _, c in order)
    print(f"<!-- {total} config fields — generated by scripts/gen_config_reference.py -->\n")

    def row(key, env, typ, default, purpose):
        t = _short(typ, 22).replace("|", "\\|")           # e.g. "str | None"
        d = _short(default, 30).replace("|", "\\|")
        p = _short(purpose, 180).replace("|", "\\|")
        print(f"| `{key}` | `{env}` | {t} | `{d}` | {p} |")

    if toplevel:
        print("### Top-level\n")
        print("| TOML key | Env var | Type | Default | Purpose |")
        print("|---|---|---|---|---|")
        for (name, typ, default, purpose) in toplevel:
            row(name, f"NMEM_{name.upper()}", typ, default, purpose)
        print()

    for (section, cls) in order:
        title = docs.get(cls, cls).rstrip(".")
        print(f"### `[{section}]` — {title}\n")
        print("| TOML key | Env var | Type | Default | Purpose |")
        print("|---|---|---|---|---|")
        for (name, typ, default, purpose) in classes[cls]:
            row(f"{section}.{name}", f"NMEM_{section.upper()}__{name.upper()}",
                typ, default, purpose)
        print()


if __name__ == "__main__":
    main()
